# Try_Except_Finally.py
Try_Except_Finally.py

output of these code :

Error: division by zero
Enter a number: 55
Result: 0.18181818181818182
Closing the file.
Enter another number: 65
Division successful! Result: 1.5384615384615385
Execution complete.

Process finished with exit code 0
